### ISSUE TITLE
在android 9.0上面会出现闪退

### ISSUE THREAD

**Issue by yi89521** [jarryleo/MagicScreenAdapter#3]
在安卓9.0上面APP打开以后会崩溃。。报Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8794 (test.testscreen), pid 8794 (test.testscreen) 错误。。
在安卓5.0上面会出现适配不成功的情况

**Comment by jarryleo** [comment]
等我找到9.0设备再测试下

**Comment by jarryleo** [comment]
9.0的模拟器没出现问题
