### ISSUE TITLE
activity内有 webview。从webview开始，后面的view全部失效

### ISSUE THREAD

**Issue by helloV7** [jarryleo/MagicScreenAdapter#6]
activity内有 webview。从webview开始，后面的view全部失效
使用方法MagicScreenAdapter.adapt(this, 375);
所用控件width设置的值都是一样的。

**Comment by helloV7** [comment]
暂时的解决方法
在application中初始化一个webview。

**Comment by jarryleo** [comment]
2.8版本已经修复
